# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_modulefeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulefeedback',
            name='feedback_other',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
