# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_auto_20171008_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='students',
            field=models.ManyToManyField(to='tool.Student'),
        ),
    ]
