# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='colourblind_opts_on',
            field=models.BooleanField(default=False),
        ),
    ]
