# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_auto_20180211_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='attendance_range_1_cap',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='settings',
            name='attendance_range_2_cap',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='settings',
            name='attendance_range_3_cap',
            field=models.IntegerField(default=75),
        ),
    ]
