# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_auto_20180215_2210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('module_code', 'module_crn')]),
        ),
    ]
